### ISSUE TITLE
What is Traffic Volume

### ISSUE THREAD

**Issue by ziyueqiu** [UMass-LIDS/Jedi#2]
You mentioned that the `traffic_volume field specifies the traffic volume for the traffic class,` but I still don't know its meaning in caching traces. Looking forward to a clarification if possible.

// update
Is it `reqs/sec`?

**Comment by anisabnis** [comment]
Yes, traffic volume is reqs/sec.

Yes you are right, for a cache trace it does not matter as the sequence of requests determines the hitrates of the cache. However it comes into the picture while mixing different traffic types. You will be able to specify the rate at which requests are made to a traffic type A when compared to say a traffic type B. And this will alter the overall cache performance as different traffic types have different caching performance.

**Comment by anisabnis** [comment]
Closing issue
