### ISSUE TITLE
[Question] trace generation

### ISSUE THREAD

**Issue by ziyueqiu** [UMass-LIDS/Jedi#3]
1. In the README.md file, the instruction is `python3 traffic_modeler.py <path_to_original_trace> <output_dir>`. However, within the repository, I only found a file named `popularity_traffic_modeler.py`. Should I assume that this is the file the instructions were referring to?

2. When executing `popularity_traffic_modeler.py`, I encountered a failure at line 121.

The error message received was as follows:

```
Traceback (most recent call last):
  File "popularity_traffic_modeler.py", line 121, in <module>
    tm  = int(l[0])
ValueError: invalid literal for int() with base 10: ''
```

Upon investigation, I discovered that the issue stems from line 117, which explicitly sets the cache size to be 10GB (`while bytes_in_cache < 10*MIL:`). It appears that the program requires the trace to have a larger footprint than this for successful execution.

I think it useful to clarify this in README, though I understand you already mentioned in the paper that req num needs to be no less than 100M and the size unit is 1KB, so 10GB is a reasonable boulder.

3. sec3.2 instructions mention copying fd.txt (actually pfd.txt shown in the output directory), however, your tragen_cli.py needs pfd.txt.gz

```
3.2. Submitting traffic models
Consider adding your footprint descriptors to our repository. To do so,

Create a directory FOOTPRINT_DESCRIPTOR/<your_traffic_class_name>.
Copy the footprint descriptor (named as fd.txt) and joint popularity-size distribution (popularity_sz.txt) to FOOTPRINT_DESCRIPTOR/<your_traffic_class_name>/.
Create an entry in [available traffic models](https://github.com/UMass-LIDS/Jedi#5-available-traffic-models).
Update the file FOOTPRINT_DESCRIPTOR/available_fds.txt
```

error:

```
Traceback (most recent call last):
  File "tragen_cli.py", line 28, in <module>
    trafficMixer = TrafficMixer(args)
  File "/users/ziyueqiu/mnt/CloudStorage/ziyue/Jedi/popularity_traffic_mixer.py", line 43, in __init__
    self.object_weight_vector()        
  File "/users/ziyueqiu/mnt/CloudStorage/ziyue/Jedi/popularity_traffic_mixer.py", line 112, in object_weight_vector
    f = gzip.open("./FOOTPRINT_DESCRIPTORS/" + self.trafficClasses[i] + "/pfd.txt.gz", "rb")            
  File "/usr/lib/python3.8/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/usr/lib/python3.8/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: './FOOTPRINT_DESCRIPTORS/test/pfd.txt.gz'
```

**Comment by anisabnis** [comment]
Yes, you have answered all the questions yourself. 
Thank you so much for pointing these out! I will update the readme accordingly.

**Comment by anisabnis** [comment]
Updated
