### ISSUE TITLE
[Question] tragen_cli.py -d <output_directory> doesn't work

### ISSUE THREAD

**Issue by ziyueqiu** [UMass-LIDS/Jedi#5]
seems like the hard-coded output directory is `./OUTPUT`

my specified directory path doesn't work

**Comment by anisabnis** [comment]
Yes, it has been hardcoded. I will update the readme.

**Comment by anisabnis** [comment]
Have fixed it. Thanks!

**Comment by anisabnis** [comment]
Closing the issue.
